---
title: "loops_and_functions"
author: "Allie Cole"
date: "8/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
transects <- c("Transect A", "Transect B", "Transect C")

matrix_a <- matrix(ncol = length(transects), nrow = length(weekdays))

for (i in seq_along(transects)) {
  for (j in seq_along(weekdays)) {
    p <- paste(weekdays[j], "-", transects[i])
    matrix_a[j, i] <- p
  }
}

matrix_a

```
### TAsk 2

```{r}
force <- function(mass, acceleration) {
  f <- mass * acceleration 
  print(paste("The resulting force is", f, "Newtons"))
}
  
force(mass = 2, acceleration = 17)
```

### TAsk 3 

```{r}
name_column <- function(df, numb) {
  if (numb < 1) {
    stop("This is not a column")
  } else if (numb > ncol(df)) {
    stop("This is not a column")
    
  } else (names(df[numb]))
}

name_column(df = mtcars, numb = 4)
```

### Task 4

```{r}
sci_name <- c("Chanos chanos", "Sphyraena barracuda", "Caranx ignobilis")
common_name <- c("Milkfish", "Great barracuda", "Giant trevally")
a_est <- c(0.0905, 0.0181, 0.0353)
b_est <- c(2.52, 3.27, 3.05)

fish_parms <- data.frame(sci_name, common_name, a_est, b_est)

fish_vec <- seq(from = 0, to = 100, by = 1)

#making a function

fish_weight <- function(fish_name, tot_length) {

  fish_select <- filter(fish_parms, common_name == fish_name)
  
  fish_weight_calc <- fish_select$a_est * (tot_length ^ fish_select$b_est)
  return(fish_weight_calc)
}

fish_weight(fish_name = "Milkfish", tot_length = 17)

milkfish_weight <- fish_weight(fish_name = "Milkfish", tot_length = fish_vec)

```


### Task 5 

```{r}
wave_power <- function(wave_h, period) {
  p <- 0.5 * (wave_h^2) * period
  return(p)
}

time <- seq(from = 0, to = 3, by = 0.2)

wave_power(wave_h = time, period = 8 )

```

### TAsk 6 

```{r}
wave_power_s <- function(wave_h, period, depth) {
  if (depth > 12){
    message("deep wave")
    p <- 0.5 * (wave_h^2) * period
  } else if (depth <= 12){
    message("shallow wave")
    p <- 0.81 * (wave_h^2) * period
  }
  return(p)
}

wave_power_s(wave_h = 13, period = 16, depth= 7)
```










